/*
 reach - JSONP made simple
 @author beehaflich
 @license MIT
*/
var reach=function(a){this.increment_=reach.increment_++;if(a){var c=["callback","url","parameter","arguments"],b,d=c.length;for(b=0;b<d;b++)a[c[b]]&&this[c[b]](a[c[b]])}};reach.increment_=0;reach.prototype.increment=function(){return this.increment_};reach.callbacks={};reach.prototype.callback=function(a){return arguments.length?(reach.callbacks[this.increment()]=a,this):reach.callbacks[this.increment()]};reach.prototype.url_=null;
reach.prototype.url=function(a){return arguments.length?(this.url_=a||null,this):this.url_};reach.prototype.arguments=function(a){if(arguments.length){this.arguments_=this.arguments_||{};for(var c in a)this.arguments_[c]=a[c];return this}return this.arguments_||{}};reach.stringify=function(a){return window.JSON?window.JSON.stringify(a):null};reach.prototype.stringify=function(a){return reach.stringify(a)};reach.prototype.parameter_="callback";
reach.prototype.parameter=function(a){return arguments.length?(this.parameter_=a,this):this.parameter_};reach.prototype.format=function(a){var c=Object.prototype.toString.call(a);if("[object String]"===c)return a;if("[object Number]"===c){if(Number.isNaN(a))throw"NaN is invalid JSON";if(!Number.isFinite(a))throw"Non-finite numbers are invalid JSON";return a}if("[object Function]"===c)throw"Function is invalid JSON";return this.stringify(a)};reach.prototype.sent_=!1;reach.prototype.sent=function(){return this.sent_};
reach.prototype.send=function(){if(this.sent_)throw"JSONP Request already sent!";var a=this.url();if(!a)throw"URL is required to send a JSONP request";var c=this.arguments(),b=[],d;for(d in c)b.push(encodeURIComponent(d)+"="+encodeURIComponent(this.format(c[d])));this.callback()&&b.push(encodeURIComponent(this.parameter())+"="+encodeURIComponent("reach.callbacks["+this.increment()+"]"));b.length&&(a=a+"?"+b.join("&"));c=document.head;if(!c)throw"Document seems to have been decapitated (missing <head>)";
b=document.createElement("script");b.type="text/javascript";b.src=a;b.dataset&&(b.dataset.requestSource="reach",b.dataset.increment=this.increment(),b.dataset.timestamp=Math.floor(Date.now()/1E3));c.appendChild(b);this.sent_=!0;return this};
